# DataSource Config
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:p6spy:h2:file:d:/mybatisplus;TRACE_LEVEL_FILE=0
    username: root
    password: test
  h2:
    console:
      enabled: true
      path: /console


# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug
# MyBatis-Plus 配置该演示无
