spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    url: jdbc:h2:mem:test
    username: root
    password: test
mybatis-plus:
  typeEnumsPackage: com.github.yulichang.mapping.enums
  global-config:
    db-config:
      logic-delete-field: del
      logic-delete-value: true
      logic-not-delete-value: false
    banner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl