spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    url: jdbc:mysql://localhost:3306/mybatis-plus?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
mybatis-plus:
  typeEnumsPackage: com.github.yulichang.join.enums
  global-config:
    db-config:
      logic-delete-field: del
      logic-delete-value: true
      logic-not-delete-value: false
    banner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl